# Generated by Django 5.0.3 on 2024-03-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='turno',
            table='turno',
        ),
    ]
