# Generated by Django 5.0.3 on 2024-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(null=True)),
                ('antecedentes_personales', models.TextField(null=True)),
                ('antecedentes_hereditarios', models.TextField(null=True)),
                ('alergia', models.TextField(null=True)),
                ('medicacion', models.TextField(null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
